"""Add comments data tables

Revision ID: c97a4379015a
Revises: b8f19b0daef9
Create Date: 2025-10-17 14:24:41.621121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c97a4379015a"
down_revision: Union[str, Sequence[str], None] = "b8f19b0daef9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False, comment="平台类型"),
        sa.Column(
            "comment_id", sa.String(length=100), nullable=False, comment="平台评论ID"
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="评论内容"),
        sa.Column(
            "note_id", sa.String(length=100), nullable=False, comment="所属笔记ID"
        ),
        sa.Column(
            "note_title", sa.String(length=500), nullable=True, comment="笔记标题"
        ),
        sa.Column(
            "parent_comment_id",
            sa.String(length=100),
            nullable=True,
            comment="父评论ID(一级评论为空)",
        ),
        sa.Column(
            "sub_comment_count", sa.Integer(), nullable=False, comment="子评论数量"
        ),
        sa.Column(
            "author_id", sa.String(length=100), nullable=False, comment="评论者ID"
        ),
        sa.Column(
            "author_name", sa.String(length=200), nullable=True, comment="评论者昵称"
        ),
        sa.Column(
            "author_avatar",
            sa.String(length=500),
            nullable=True,
            comment="评论者头像URL",
        ),
        sa.Column("liked_count", sa.Integer(), nullable=False, comment="点赞数"),
        sa.Column("reply_count", sa.Integer(), nullable=False, comment="回复数"),
        sa.Column(
            "ip_location", sa.String(length=100), nullable=True, comment="IP属地"
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True, comment="评论发布时间"),
        sa.Column("crawled_at", sa.DateTime(), nullable=False, comment="首次爬取时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="数据更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index("idx_comments_author_id", "comments", ["author_id"], unique=False)
    op.create_index("idx_comments_crawled_at", "comments", ["crawled_at"], unique=False)
    op.create_index("idx_comments_note_id", "comments", ["note_id"], unique=False)
    op.create_index(
        "idx_comments_parent_comment_id",
        "comments",
        ["parent_comment_id"],
        unique=False,
    )
    op.create_index(
        "idx_comments_platform_comment_id",
        "comments",
        ["platform", "comment_id"],
        unique=False,
    )
    op.create_index(
        "idx_comments_published_at", "comments", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_comment_id"), "comments", ["comment_id"], unique=True
    )
    op.create_index(op.f("ix_comments_note_id"), "comments", ["note_id"], unique=False)
    op.create_index(
        op.f("ix_comments_parent_comment_id"),
        "comments",
        ["parent_comment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comments_platform"), "comments", ["platform"], unique=False
    )
    op.create_table(
        "task_comments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("comment_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "crawled_at",
            sa.DateTime(),
            nullable=False,
            comment="该任务爬取此评论的时间",
        ),
        sa.Column(
            "keyword",
            sa.String(length=200),
            nullable=True,
            comment="爬取时使用的关键词",
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_task_comments_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawler_tasks.id"],
            name=op.f("fk_task_comments_task_id_crawler_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_comments")),
    )
    op.create_index(
        "idx_task_comments_comment_id", "task_comments", ["comment_id"], unique=False
    )
    op.create_index(
        "idx_task_comments_task_comment",
        "task_comments",
        ["task_id", "comment_id"],
        unique=True,
    )
    op.create_index(
        "idx_task_comments_task_id", "task_comments", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_task_comments_task_id", table_name="task_comments")
    op.drop_index("idx_task_comments_task_comment", table_name="task_comments")
    op.drop_index("idx_task_comments_comment_id", table_name="task_comments")
    op.drop_table("task_comments")
    op.drop_index(op.f("ix_comments_platform"), table_name="comments")
    op.drop_index(op.f("ix_comments_parent_comment_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_note_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_comment_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_index("idx_comments_published_at", table_name="comments")
    op.drop_index("idx_comments_platform_comment_id", table_name="comments")
    op.drop_index("idx_comments_parent_comment_id", table_name="comments")
    op.drop_index("idx_comments_note_id", table_name="comments")
    op.drop_index("idx_comments_crawled_at", table_name="comments")
    op.drop_index("idx_comments_author_id", table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
