"""Add notes and task_notes tables

Revision ID: fdbbd9b5c382
Revises: 2025_10_07_001
Create Date: 2025-10-17 13:17:37.990320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdbbd9b5c382"
down_revision: Union[str, Sequence[str], None] = "2025_10_07_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False, comment="平台类型"),
        sa.Column(
            "note_id", sa.String(length=100), nullable=False, comment="平台笔记ID"
        ),
        sa.Column("title", sa.String(length=500), nullable=False, comment="笔记标题"),
        sa.Column("content", sa.Text(), nullable=True, comment="笔记内容"),
        sa.Column(
            "note_type",
            sa.String(length=50),
            nullable=True,
            comment="笔记类型(video/image/note)",
        ),
        sa.Column("author_id", sa.String(length=100), nullable=True, comment="作者ID"),
        sa.Column(
            "author_name", sa.String(length=200), nullable=True, comment="作者昵称"
        ),
        sa.Column("liked_count", sa.Integer(), nullable=False, comment="点赞数"),
        sa.Column("collected_count", sa.Integer(), nullable=False, comment="收藏数"),
        sa.Column("comment_count", sa.Integer(), nullable=False, comment="评论数"),
        sa.Column("shared_count", sa.Integer(), nullable=False, comment="分享数"),
        sa.Column("view_count", sa.Integer(), nullable=False, comment="浏览数"),
        sa.Column("images", sa.Text(), nullable=True, comment="图片URL列表(JSON)"),
        sa.Column("video_url", sa.String(length=500), nullable=True, comment="视频URL"),
        sa.Column("note_url", sa.String(length=500), nullable=True, comment="笔记链接"),
        sa.Column(
            "ip_location", sa.String(length=100), nullable=True, comment="IP属地"
        ),
        sa.Column("tags", sa.Text(), nullable=True, comment="标签列表(JSON)"),
        sa.Column("published_at", sa.DateTime(), nullable=True, comment="笔记发布时间"),
        sa.Column(
            "last_modified_at", sa.DateTime(), nullable=True, comment="笔记最后修改时间"
        ),
        sa.Column("crawled_at", sa.DateTime(), nullable=False, comment="首次爬取时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="数据更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index("idx_author_id", "notes", ["author_id"], unique=False)
    op.create_index("idx_crawled_at", "notes", ["crawled_at"], unique=False)
    op.create_index(
        "idx_platform_note_id", "notes", ["platform", "note_id"], unique=False
    )
    op.create_index("idx_published_at", "notes", ["published_at"], unique=False)
    op.create_index(op.f("ix_notes_author_id"), "notes", ["author_id"], unique=False)
    op.create_index(op.f("ix_notes_note_id"), "notes", ["note_id"], unique=True)
    op.create_index(op.f("ix_notes_platform"), "notes", ["platform"], unique=False)
    op.create_table(
        "task_notes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("note_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "crawled_at",
            sa.DateTime(),
            nullable=False,
            comment="该任务爬取此笔记的时间",
        ),
        sa.Column(
            "keyword",
            sa.String(length=200),
            nullable=True,
            comment="爬取时使用的关键词",
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.id"],
            name=op.f("fk_task_notes_note_id_notes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawler_tasks.id"],
            name=op.f("fk_task_notes_task_id_crawler_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_notes")),
    )
    op.create_index("idx_note_id", "task_notes", ["note_id"], unique=False)
    op.create_index("idx_task_id", "task_notes", ["task_id"], unique=False)
    op.create_index("idx_task_note", "task_notes", ["task_id", "note_id"], unique=True)
    op.drop_index(op.f("ix_crawler_accounts_active"), table_name="crawler_accounts")
    op.create_index(
        op.f("ix_crawler_accounts_id"), "crawler_accounts", ["id"], unique=False
    )
    op.drop_table_comment(
        "crawler_accounts", existing_comment="爬虫账号资源表", schema=None
    )
    op.drop_index(
        op.f("ix_crawler_note_results_note_id"), table_name="crawler_note_results"
    )
    op.drop_index(
        op.f("ix_crawler_note_results_task_id"), table_name="crawler_note_results"
    )
    op.create_index(
        op.f("ix_crawler_note_results_id"), "crawler_note_results", ["id"], unique=False
    )
    op.drop_index(
        op.f("ix_crawler_proxy_providers_active"), table_name="crawler_proxy_providers"
    )
    op.create_index(
        op.f("ix_crawler_proxy_providers_id"),
        "crawler_proxy_providers",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawler_proxy_providers_is_active"),
        "crawler_proxy_providers",
        ["is_active"],
        unique=False,
    )
    op.drop_table_comment(
        "crawler_proxy_providers", existing_comment="代理服务商配置表", schema=None
    )
    op.drop_index(
        op.f("ix_crawler_task_logs_created_at"), table_name="crawler_task_logs"
    )
    op.drop_index(op.f("ix_crawler_task_logs_task_id"), table_name="crawler_task_logs")
    op.create_index(
        op.f("ix_crawler_task_logs_id"), "crawler_task_logs", ["id"], unique=False
    )
    op.drop_table_comment(
        "crawler_task_logs", existing_comment="任务执行日志表", schema=None
    )
    op.drop_index(op.f("ix_crawler_tasks_created_by"), table_name="crawler_tasks")
    op.create_index(op.f("ix_crawler_tasks_id"), "crawler_tasks", ["id"], unique=False)
    op.drop_constraint(
        op.f("fk_crawler_tasks_created_by_users"), "crawler_tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_crawler_tasks_created_by_users"),
        "crawler_tasks",
        "users",
        ["created_by"],
        ["id"],
    )
    op.drop_table_comment("crawler_tasks", existing_comment="爬虫任务表", schema=None)
    op.drop_index(op.f("idx_rbac_permission_chain"), table_name="role_permissions")
    op.drop_index(
        op.f("idx_role_permissions_role_lookup"), table_name="role_permissions"
    )
    op.drop_constraint(op.f("uq_roles_name"), "roles", type_="unique")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.drop_index(op.f("idx_user_roles_user_lookup"), table_name="user_roles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_user_roles_user_lookup"), "user_roles", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_unique_constraint(
        op.f("uq_roles_name"), "roles", ["name"], postgresql_nulls_not_distinct=False
    )
    op.create_index(
        op.f("idx_role_permissions_role_lookup"),
        "role_permissions",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_rbac_permission_chain"),
        "role_permissions",
        ["role_id", "permission_id"],
        unique=False,
    )
    op.create_table_comment(
        "crawler_tasks", "爬虫任务表", existing_comment=None, schema=None
    )
    op.drop_constraint(
        op.f("fk_crawler_tasks_created_by_users"), "crawler_tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_crawler_tasks_created_by_users"),
        "crawler_tasks",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_crawler_tasks_id"), table_name="crawler_tasks")
    op.create_index(
        op.f("ix_crawler_tasks_created_by"),
        "crawler_tasks",
        ["created_by"],
        unique=False,
    )
    op.create_table_comment(
        "crawler_task_logs", "任务执行日志表", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_crawler_task_logs_id"), table_name="crawler_task_logs")
    op.create_index(
        op.f("ix_crawler_task_logs_task_id"),
        "crawler_task_logs",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawler_task_logs_created_at"),
        "crawler_task_logs",
        ["created_at"],
        unique=False,
    )
    op.create_table_comment(
        "crawler_proxy_providers",
        "代理服务商配置表",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(
        op.f("ix_crawler_proxy_providers_is_active"),
        table_name="crawler_proxy_providers",
    )
    op.drop_index(
        op.f("ix_crawler_proxy_providers_id"), table_name="crawler_proxy_providers"
    )
    op.create_index(
        op.f("ix_crawler_proxy_providers_active"),
        "crawler_proxy_providers",
        ["is_active"],
        unique=False,
    )
    op.drop_index(op.f("ix_crawler_note_results_id"), table_name="crawler_note_results")
    op.create_index(
        op.f("ix_crawler_note_results_task_id"),
        "crawler_note_results",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawler_note_results_note_id"),
        "crawler_note_results",
        ["note_id"],
        unique=False,
    )
    op.create_table_comment(
        "crawler_accounts", "爬虫账号资源表", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_crawler_accounts_id"), table_name="crawler_accounts")
    op.create_index(
        op.f("ix_crawler_accounts_active"),
        "crawler_accounts",
        ["is_active"],
        unique=False,
    )
    op.drop_index("idx_task_note", table_name="task_notes")
    op.drop_index("idx_task_id", table_name="task_notes")
    op.drop_index("idx_note_id", table_name="task_notes")
    op.drop_table("task_notes")
    op.drop_index(op.f("ix_notes_platform"), table_name="notes")
    op.drop_index(op.f("ix_notes_note_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_author_id"), table_name="notes")
    op.drop_index("idx_published_at", table_name="notes")
    op.drop_index("idx_platform_note_id", table_name="notes")
    op.drop_index("idx_crawled_at", table_name="notes")
    op.drop_index("idx_author_id", table_name="notes")
    op.drop_table("notes")
    # ### end Alembic commands ###
