"""add_source_plan_to_strategies

Revision ID: 5f3ad98405e9
Revises: 20260323_strat_research_eng
Create Date: 2026-03-26 08:17:48.542755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f3ad98405e9'
down_revision: Union[str, Sequence[str], None] = '20260323_strat_research_eng'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_analysis', 'post_id',
               existing_type=sa.INTEGER(),
               comment='关联的原文ID',
               existing_comment='关联的帖子ID',
               existing_nullable=False)
    op.alter_column('post_analysis', 'post_deep_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='原文深度分析结果：实体、观点、摘要',
               existing_comment='帖子深度分析结果：实体、观点、摘要',
               existing_nullable=True)
    op.alter_column('social_data_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='任务状态: pending/accepted/running/probe_ready/approved/completed/failed',
               existing_comment='任务状态: pending/accepted/running/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('social_posts', 'post_id_on_platform',
               existing_type=sa.VARCHAR(length=255),
               comment='平台上的原文ID',
               existing_comment='平台上的帖子ID',
               existing_nullable=False)
    op.alter_column('social_posts', 'post_type',
               existing_type=sa.VARCHAR(length=50),
               comment='原文类型',
               existing_comment='帖子类型',
               existing_nullable=True)
    op.alter_column('social_posts', 'url',
               existing_type=sa.TEXT(),
               comment='原文URL',
               existing_comment='帖子URL',
               existing_nullable=True)
    op.add_column('strategies', sa.Column('source_plan', sa.JSON(), nullable=True, comment='AI 建议的数据源组合，[{type, rationale}]，Layer 0 Brief 摄入时生成'))
    op.alter_column('strategies', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: draft / planned / probing / collecting / ready / phase1_done / phase2_done / completed',
               existing_comment='状态: briefing / consulting / monitors_created / slices_ready / phase1_done / phase2_done / completed',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategies', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: briefing / consulting / monitors_created / slices_ready / phase1_done / phase2_done / completed',
               existing_comment='状态: draft / planned / probing / collecting / ready / phase1_done / phase2_done / completed',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_column('strategies', 'source_plan')
    op.alter_column('social_posts', 'url',
               existing_type=sa.TEXT(),
               comment='帖子URL',
               existing_comment='原文URL',
               existing_nullable=True)
    op.alter_column('social_posts', 'post_type',
               existing_type=sa.VARCHAR(length=50),
               comment='帖子类型',
               existing_comment='原文类型',
               existing_nullable=True)
    op.alter_column('social_posts', 'post_id_on_platform',
               existing_type=sa.VARCHAR(length=255),
               comment='平台上的帖子ID',
               existing_comment='平台上的原文ID',
               existing_nullable=False)
    op.alter_column('social_data_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='任务状态: pending/accepted/running/completed/failed',
               existing_comment='任务状态: pending/accepted/running/probe_ready/approved/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_analysis', 'post_deep_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='帖子深度分析结果：实体、观点、摘要',
               existing_comment='原文深度分析结果：实体、观点、摘要',
               existing_nullable=True)
    op.alter_column('post_analysis', 'post_id',
               existing_type=sa.INTEGER(),
               comment='关联的帖子ID',
               existing_comment='关联的原文ID',
               existing_nullable=False)
    # ### end Alembic commands ###
