"""strategy_new_fields_and_status

Revision ID: 4a80e776ebe4
Revises: 20260305_proj_to_mon
Create Date: 2026-03-05 17:15:36.585714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a80e776ebe4'
down_revision: Union[str, Sequence[str], None] = '20260305_proj_to_mon'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_jobs', 'analysis_type',
               existing_type=sa.VARCHAR(length=50),
               comment='分析类型: screening_posts/deep_posts/deep_comments/topic_clustering/competitive',
               existing_comment='分析类型',
               existing_nullable=False)
    op.alter_column('analysis_jobs', 'analysis_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='分析配置参数（如聚类数量、竞品关键词等）',
               existing_comment='分析配置参数',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'source_task_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='源任务ID列表（项目级分析时指定的任务范围）',
               existing_comment='源任务ID列表',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='状态: pending/processing/completed/failed',
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('analysis_jobs', 'token_usage',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Token使用统计（包含成本信息）',
               existing_comment='Token使用统计',
               existing_nullable=True)
    op.drop_index(op.f('idx_analysis_job_monitor'), table_name='analysis_jobs')
    op.create_index('idx_analysis_job_project', 'analysis_jobs', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_analysis_type'), 'analysis_jobs', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_monitor_id'), 'analysis_jobs', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_task_id'), 'analysis_jobs', ['task_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_user_id'), 'analysis_jobs', ['user_id'], unique=False)
    op.alter_column('analysis_slices', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='切片名称（可选）',
               existing_comment='快照名称（可选）',
               existing_nullable=True)
    op.alter_column('analysis_slices', 'user_id',
               existing_type=sa.INTEGER(),
               comment='创建切片的用户ID',
               existing_comment='创建快照的用户ID',
               existing_nullable=False)
    op.alter_column('analysis_slices', 'result_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='切片结果数据',
               existing_comment='快照结果数据',
               existing_nullable=False)
    op.drop_index(op.f('idx_analysis_slices_created_at'), table_name='analysis_slices')
    op.drop_index(op.f('idx_analysis_slices_monitor'), table_name='analysis_slices')
    op.create_index('idx_monitor_slices_created_at', 'analysis_slices', ['created_at'], unique=False)
    op.create_index('idx_monitor_slices_project', 'analysis_slices', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_analysis_slices_monitor_id'), 'analysis_slices', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_analysis_slices_user_id'), 'analysis_slices', ['user_id'], unique=False)
    op.drop_index(op.f('ix_social_projects_name'), table_name='monitors')
    op.drop_index(op.f('ix_social_projects_owner_id'), table_name='monitors')
    op.drop_constraint(op.f('uq_social_projects_name'), 'monitors', type_='unique')
    op.create_index(op.f('ix_monitors_name'), 'monitors', ['name'], unique=True)
    op.create_index(op.f('ix_monitors_owner_id'), 'monitors', ['owner_id'], unique=False)
    op.drop_constraint(op.f('uq_platforms_code'), 'platforms', type_='unique')
    op.drop_constraint(op.f('uq_platforms_name'), 'platforms', type_='unique')
    op.drop_index(op.f('ix_platforms_code'), table_name='platforms')
    op.create_index(op.f('ix_platforms_code'), 'platforms', ['code'], unique=True)
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.alter_column('post_analysis', 'spam_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='广告分（0-10，分数越高越像广告/营销内容）',
               existing_comment='垃圾分（0-10，分数越高越像垃圾）',
               existing_nullable=True)
    op.alter_column('post_analysis', 'value_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='价值分（0-10，分数越高内容价值越大）',
               existing_comment='价值分（0-10，分数越高价值越大）',
               existing_nullable=True)
    op.alter_column('post_analysis', 'sentiment',
               existing_type=sa.INTEGER(),
               comment='情感倾向（-2: 强烈负面, -1: 负面, 0: 中性, 1: 正面, 2: 强烈正面）',
               existing_comment='情感倾向（-1: 负面, 0: 中性, 1: 正面）',
               existing_nullable=True)
    op.alter_column('post_analysis', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后分析时间',
               existing_comment='分析完成时间',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_post_analysis_post_id'), 'post_analysis', type_='unique')
    op.create_index(op.f('ix_post_analysis_post_id'), 'post_analysis', ['post_id'], unique=True)
    op.create_index(op.f('ix_post_analysis_task_id'), 'post_analysis', ['task_id'], unique=False)
    op.drop_index(op.f('idx_rbac_permission_chain'), table_name='role_permissions')
    op.drop_index(op.f('idx_role_permissions_role_lookup'), table_name='role_permissions')
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('social_data_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='任务状态: pending/accepted/running/completed/failed',
               existing_comment='任务状态: pending/running/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('social_data_tasks', 'analysis_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务级AI分析聚合结果（NSR、SERP、实体、IPA等）',
               existing_comment='任务级AI分析聚合结果（NSR、SERP、实体、KANO等）',
               existing_nullable=True)
    op.alter_column('social_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               comment='点赞数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('social_posts', 'comments_count',
               existing_type=sa.INTEGER(),
               comment='评论数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('social_posts', 'shares_count',
               existing_type=sa.INTEGER(),
               comment='分享/转发数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('social_posts', 'views_count',
               existing_type=sa.INTEGER(),
               comment='播放/浏览数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('strategies', sa.Column('consultation_rounds', sa.JSON(), server_default='[]', nullable=False, comment='AI 咨询轮次记录'))
    op.add_column('strategies', sa.Column('suggested_monitor_ids', sa.JSON(), server_default='[]', nullable=False, comment='AI 建议并已创建的监测 ID'))
    op.add_column('strategies', sa.Column('slice_plan', sa.JSON(), server_default='[]', nullable=False, comment='切片规划草案（咨询产出）'))
    op.add_column('strategies', sa.Column('evaluation_result', sa.JSON(), nullable=True, comment='AI 充分性评估结果'))
    op.alter_column('strategies', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: briefing / consulting / monitors_created / slices_ready / phase1_done / phase2_done / completed',
               existing_comment='状态: draft / phase1_done / phase2_done / completed',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('strategies', 'brand_brief',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='结构化 Brand Brief',
               existing_comment='可选 Brand Brief',
               existing_nullable=True)
    op.drop_index(op.f('idx_user_roles_user_lookup'), table_name='user_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_roles_user_lookup'), 'user_roles', ['user_id'], unique=False)
    op.alter_column('strategies', 'brand_brief',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='可选 Brand Brief',
               existing_comment='结构化 Brand Brief',
               existing_nullable=True)
    op.alter_column('strategies', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: draft / phase1_done / phase2_done / completed',
               existing_comment='状态: briefing / consulting / monitors_created / slices_ready / phase1_done / phase2_done / completed',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_column('strategies', 'evaluation_result')
    op.drop_column('strategies', 'slice_plan')
    op.drop_column('strategies', 'suggested_monitor_ids')
    op.drop_column('strategies', 'consultation_rounds')
    op.alter_column('social_posts', 'views_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='播放/浏览数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('social_posts', 'shares_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='分享/转发数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('social_posts', 'comments_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='评论数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('social_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='点赞数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('social_data_tasks', 'analysis_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务级AI分析聚合结果（NSR、SERP、实体、KANO等）',
               existing_comment='任务级AI分析聚合结果（NSR、SERP、实体、IPA等）',
               existing_nullable=True)
    op.alter_column('social_data_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='任务状态: pending/running/completed/failed',
               existing_comment='任务状态: pending/accepted/running/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_role_permissions_role_lookup'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('idx_rbac_permission_chain'), 'role_permissions', ['role_id', 'permission_id'], unique=False)
    op.drop_index(op.f('ix_post_analysis_task_id'), table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_post_id'), table_name='post_analysis')
    op.create_unique_constraint(op.f('uq_post_analysis_post_id'), 'post_analysis', ['post_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('post_analysis', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='分析完成时间',
               existing_comment='最后分析时间',
               existing_nullable=True)
    op.alter_column('post_analysis', 'sentiment',
               existing_type=sa.INTEGER(),
               comment='情感倾向（-1: 负面, 0: 中性, 1: 正面）',
               existing_comment='情感倾向（-2: 强烈负面, -1: 负面, 0: 中性, 1: 正面, 2: 强烈正面）',
               existing_nullable=True)
    op.alter_column('post_analysis', 'value_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='价值分（0-10，分数越高价值越大）',
               existing_comment='价值分（0-10，分数越高内容价值越大）',
               existing_nullable=True)
    op.alter_column('post_analysis', 'spam_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='垃圾分（0-10，分数越高越像垃圾）',
               existing_comment='广告分（0-10，分数越高越像广告/营销内容）',
               existing_nullable=True)
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=False)
    op.drop_index(op.f('ix_platforms_code'), table_name='platforms')
    op.create_index(op.f('ix_platforms_code'), 'platforms', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_platforms_name'), 'platforms', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_platforms_code'), 'platforms', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_monitors_owner_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_name'), table_name='monitors')
    op.create_unique_constraint(op.f('uq_social_projects_name'), 'monitors', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_social_projects_owner_id'), 'monitors', ['owner_id'], unique=False)
    op.create_index(op.f('ix_social_projects_name'), 'monitors', ['name'], unique=False)
    op.drop_index(op.f('ix_analysis_slices_user_id'), table_name='analysis_slices')
    op.drop_index(op.f('ix_analysis_slices_monitor_id'), table_name='analysis_slices')
    op.drop_index('idx_monitor_slices_project', table_name='analysis_slices')
    op.drop_index('idx_monitor_slices_created_at', table_name='analysis_slices')
    op.create_index(op.f('idx_analysis_slices_monitor'), 'analysis_slices', ['monitor_id'], unique=False)
    op.create_index(op.f('idx_analysis_slices_created_at'), 'analysis_slices', ['created_at'], unique=False)
    op.alter_column('analysis_slices', 'result_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='快照结果数据',
               existing_comment='切片结果数据',
               existing_nullable=False)
    op.alter_column('analysis_slices', 'user_id',
               existing_type=sa.INTEGER(),
               comment='创建快照的用户ID',
               existing_comment='创建切片的用户ID',
               existing_nullable=False)
    op.alter_column('analysis_slices', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='快照名称（可选）',
               existing_comment='切片名称（可选）',
               existing_nullable=True)
    op.drop_index(op.f('ix_analysis_jobs_user_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_task_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_monitor_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_analysis_type'), table_name='analysis_jobs')
    op.drop_index('idx_analysis_job_project', table_name='analysis_jobs')
    op.create_index(op.f('idx_analysis_job_monitor'), 'analysis_jobs', ['monitor_id'], unique=False)
    op.alter_column('analysis_jobs', 'token_usage',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Token使用统计',
               existing_comment='Token使用统计（包含成本信息）',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='状态',
               existing_comment='状态: pending/processing/completed/failed',
               existing_nullable=False)
    op.alter_column('analysis_jobs', 'source_task_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='源任务ID列表',
               existing_comment='源任务ID列表（项目级分析时指定的任务范围）',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'analysis_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='分析配置参数',
               existing_comment='分析配置参数（如聚类数量、竞品关键词等）',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'analysis_type',
               existing_type=sa.VARCHAR(length=50),
               comment='分析类型',
               existing_comment='分析类型: screening_posts/deep_posts/deep_comments/topic_clustering/competitive',
               existing_nullable=False)
    # ### end Alembic commands ###
